from typing import Callable, Any, Optional

class Task:
    def delay(*args:Any, **kwargs:Any): ...
    def retry(*args:Any, **kwargs:Any): ...
    def __call__(self, *args:Any, **kwargs:Any): ...

def shared_task(func:Optional[Callable]=None, bind:bool=False, max_retries:int=0, default_retry_delay:float=0) -> Task: ...

