from typing import Any, Dict, Tuple, Union, List

class Form:
    cleaned_data: Dict[str, Any]
    def __init__(self, *args:Any, **kwargs:Any): ...
    def is_valid(self) -> bool: ...
    def add_error(self, field:str, msg:str) -> None: ...

class ModelForm(Form):
    ...

class Field:
    def __init__(self, *args:Any, **kwargs:Any): ...
    def __get__(self, instance:Any, owner:Any) -> Any: ...

class BooleanField(Field): ...
class CharField(Field): ...
class DecimalField(Field): ...
class IntegerField(Field): ...
class DateTimeField(Field): ...
class ModelChoiceField(Field): ...
class ModelMultipleChoiceField(Field): ...

class Widget:
    ...

ChoiceType = Union[Tuple[Tuple[Any, str], ...], List[Tuple[Any, str]]]

class Select(Widget):
    def __init__(self, choices: ChoiceType=(), **kwargs: Any): ...

class DateInput(Widget):
    def __init__(self, format: str=''): ...

class ValidationError(Exception): ...

