from typing import Any, Dict

class Form:
    cleaned_data: Dict[str, Any]
    def __init__(self, *args:Any, **kwargs:Any): ...
    def is_valid(self) -> bool: ...
    def add_error(self, field:str, msg:str) -> None: ...

class ModelForm(Form):
    ...

class Field:
    def __init__(self, *args:Any, **kwargs:Any): ...
    def __get__(self, instance:Any, owner:Any) -> Any: ...

class BooleanField(Field): ...
class CharField(Field): ...
class DecimalField(Field): ...
class IntegerField(Field): ...

class ValidationError(Exception): ...
