from typing import Callable, Any

class Library:
    def filter(*args:Any, **kwargs:Any) -> Callable: ...
    def tag(*args:Any, **kwargs:Any) -> Callable: ...

class Node:
    def render(self, context:Any) -> str: ...
