from typing import Dict, Any

class Exchange:
    aiohttp_proxy: str
    async def fetch_ticker(self, symbol_name:str, **kw) -> Dict[str, Any]: ...
    async def fetch_order_book(self, symbol_name:str, limit:int=None, **kw) -> Dict[str, Any]: ...
