
class Logger:
    def debug(fmt:str, *args, **kwargs) -> None: ...
    def info(fmt:str, *args, **kwargs) -> None: ...
    def warning(fmt:str, *args, **kwargs) -> None: ...
    def error(fmt:str, *args, **kwargs) -> None: ...
    def exception(fmt:str, *args, **kwargs) -> None: ...

def getLogger(name:str) -> Logger: ...
