class TestCase:
   def setUp(self): ...
   def tearDown(self): ...

class TransactionTestCase(TestCase):
   pass

class Client:
   def login(self, *args, **kargs): ...
   def post(self, *args, **kwargs): ...
   def get(self, *args, **kwargs): ...
