from typing import Any

class Signal():
    def __init__(self, providing_args:Any=None, use_caching:bool=False): ...
    def connect(self, receiver:Any, sender:Any=None, weak:bool=True, dispatch_uid:Any=None): ...

    def send(self, sender:Any, **named): ...
